### ISSUE TITLE
Issue using cargo to install

### ISSUE THREAD

**Issue by bneil** [amethyst/tools#17] opened 2016-02-23 04:35 UTC
Im currently using cargo 0.7.0-nightly (1af03be 2015-12-08)
using the following command:

```
cargo install amethyst_tools --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to unpack package `amethyst_tools v0.2.4`

Caused by:
  No such file or directory (os error 2)
```

However I was able to install when specifying the repo directly

`cargo install --git https://github.com/ebkalderon/amethyst_tools
`

I also spun up an ubuntu vm with a clean install of rust/cargo and got the same error as the above

**Comment by ebkalderon** [comment] 2016-02-23 05:22
@bneil Uh oh! Thanks for reporting this. That's not at all supposed to happen. I'll take a look at this tomorrow.

**Comment by White-Oak** [comment] 2016-02-23 07:26
I was able to get this error using this particular nightly (2015-12-08) (I actually think it's from Rust Nightly 1.6, why does ubuntu uses packages so old?), but only once. Later on, no matter what I'd do, there is no error, unfortunately.

**Comment by ebkalderon** [comment] 2016-02-23 15:29
@White-Oak @bneil Have either of you been able to reproduce this bug since?

I tried it this morning on the latest nightly as of this writing, which is `1.8.0-nightly (c8fc4817d 2016-02-22)`. Everything worked fine.

**Comment by White-Oak** [comment] 2016-02-23 16:18
@ebkalderon booted to Linux and was able to get this error on `nightly-2015-12-08`, on current stable and beta channels, but not on the current nightly.
Maybe there was a fix or a change in cargo recently (after Jan 20)?

**Comment by White-Oak** [comment] 2016-02-23 17:00
Ah, found it https://github.com/rust-lang/cargo/issues/2326.
@ebkalderon you need to republish a crate for it to be opened with cargos compiled prior to 2016-01-25.

**Comment by ebkalderon** [comment] 2016-02-23 17:07
@White-Oak I was unaware of this. Thanks! I'll take care of that now.

**Comment by ebkalderon** [comment] 2016-02-23 18:12
Commits 1c836b6, dce8366, and afb1db5 should hopefully fix this. Since we have merged several pull requests since 0.2.4, I've updated the crate version to 0.3.0 and pushed it to Crates.io. If this crate unpacks correctly for you, let me know and I'll close this issue.

**Comment by ghost** [comment] 2016-02-23 18:39
Works for me now, had the same issues.

**Comment by ebkalderon** [comment] 2016-02-23 19:18
@Krummer Great! I'm glad it works for you. Is anyone else still having issues?

**Comment by ebkalderon** [comment] 2016-02-23 21:21
Looks like this issue is resolved. I'll be closing this, but if anyone runs into this problem, feel free to reopen it.

**Closed as completed by ebkalderon** 2016-02-23 21:21 UTC
Labels: type: bug, status: resolved, diff: medium, pri: normal
